buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.4-SNAPSHOT'
    }
}

apply plugin: 'java-library'
apply plugin: 'fabric-loom'

loom {
    accessWidenerPath = file("src/main/resources/vein_mine.accesswidener")
}

base {
    archivesName = "${mod_name}-common-1.20-${mc_1_20_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version_1_20)
    withSourcesJar()
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${mc_1_20_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version_1_20}"
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

sourcesJar {
    from(rootProject.file('LICENSE')) {}
}

jar {
    from(rootProject.file('LICENSE')) {}
    manifest {
        attributes(['Specification-Title'   : mod_name,
                    'Specification-Version' : project.jar.archiveVersion,
                    'Implementation-Title'  : project.name,
                    'Implementation-Version': project.jar.archiveVersion,
                    'Built-On-Minecraft'    : mc_1_20_version])
    }
}

processResources {
    var expandProps = ['version'              : version,
                       'minecraft_version'    : mc_1_20_version,
                       'fabric_version'       : fabric_version_1_20,
                       'fabric_loader_version': fabric_loader_version_1_20,
                       'mod_name'             : mod_name,
                       'mod_id'               : mod_id,
                       'license'              : license,
                       'java_version'         : java_version_1_20]

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}
